### ISSUE TITLE
Unicode-Support for Marked-Macro

### ISSUE THREAD

**Issue by Timtam** [borisdiakur/marked#4] opened 2016-11-25 09:38 UTC
Hi,

I recently tried embedding a UTF8-formatted document via the marked macro into our Confluence wiki.
I encountered the problem that the Macro doesn't support to enter the document's encoding, like e.g. the HTML-Macro from Confluence does. This results in fetching the document in pure ANSI, which forces UTF8-Characters to display totally garbled.
Is it possible to add a parameter to the macro to give it the encoding to query the document with, which should be ANSI per default?

Otherwise we'll always have to build the plugin on our own when we're about to update the wiki.

Thanks.

Best Regards.

Toni

**Comment by borisdiakur** [comment] 2016-11-26 10:43
Hi Toni. Thanks for the issue. I will look into it, as soon as I can.

**Comment by borisdiakur** [comment] 2016-11-28 11:32
Hi Toni.

I can not reproduce your issue. Here is what I’ve done:

- I’ve created [a gist](https://gist.githubusercontent.com/borisdiakur/59cee261dccda4f568f3d4e24069a536/raw/317688a4533a50995e3e169b5cdf373b0f720b6d/tmp.md) with a markdown file with the following content: 
  > ♠ ♣ ♥ ♦
- I’ve downloaded the raw gist file and checked the encoding to make sure it is UTF-8 in Terminal with `file -I tmp.md` (I’m on OSX).
- Then I’ve loaded it in Confluence via the macro and it correctly displayed the symbols.

Maybe I’m doing something wrong. Maybe you can help me reproduce the issue? Can you give me a URL to a resource which displays incorrectly?

**Comment by Timtam** [comment] 2016-11-28 12:20
Hi Boris,

i'm also quite confused right now. We tested it 5 minutes ago in our organisation, our gitblit (which is the service we request the document from) delivers it in utf8 which should work without any problem, but it looks like hell.
We encountered that Java processes strings internally in UTF-16, which was an idea of a college of mine that this will destroy the whole encoding of the document, but as you proofed to me it seems to work for you, lol.
it's confusing, but it would be nice if you could test it by using umlauts (ä ö ü ß), since i'm a native german speaker, our organisation is german and i'm mainly writing german documents and the problem I encountered happened using umlauts.
If it works for you using umlauts it's really strange and might possible be our confluence configuration. At this moment we're using Confluence 5.9.14 and the latest Marketplace version of your plugin available for this Confluence version.

Me and my college are experimenting though, playing around with our unicode configuration, requesting documents in wrong encodings and stuff. Anyway, it seems to be more complicated than expected...

Thanks for your help.

Best Regards.
Toni

**Comment by borisdiakur** [comment] 2016-11-28 13:13
Works for me with marked@1.1.1 (I’ve updated the [gist](https://gist.githubusercontent.com/borisdiakur/59cee261dccda4f568f3d4e24069a536/raw/b37fb225a3d457f903f465a87cb78938df60187c/tmp.md)).

![screen shot 2016-11-28 at 13 57 39](https://cloud.githubusercontent.com/assets/527049/20669466/a68dd002-b574-11e6-9baa-d690286efed9.png)

Maybe [you should create a gist yourself](https://gist.github.com/) including the problematic source and try to fetch the document from gist.githubusercontent.com/<your_gist_id>/raw/your_document.md ? If this works, then it would indicate, that gitblib is not serving in UTF-8. And if it doesn’t, you could share the gist with me.

**Comment by grimurd** [comment] 2016-12-02 14:42
I have the same problem, I tried it with files both on gitlab.com and github.com. Since I'm using this for a private on-premise gitlab repository I'm unable to use this with githubusercontent.com

I had the same result using the gitlab API and linking to the raw web-version of the file.

What is rendered for me:
![image](https://cloud.githubusercontent.com/assets/4043301/20837692/0f69fb34-b89d-11e6-9d5f-f747300c9fb0.png)

[My test file](https://gist.githubusercontent.com/grimurd/f6ce77b99ca532e4cc673d0de52b487b/raw/11c266560a65c1d187e391fc934cd554ee6879a4/test)

**Comment by borisdiakur** [comment] 2016-12-02 16:44
Sorry, still cannot reproduce your issues. Tried with confluence 5.10.4 and 6.0.1, also with different browsers, on Windows and OSX, fetched data from Github and GitLab. With no luck. What I see is this (no Photoshop involved):

![screen shot 2016-12-02 at 17 26 38](https://cloud.githubusercontent.com/assets/527049/20842092/8dfc56e0-b8b6-11e6-8363-b70f7ccb19a0.png)

Maybe @sirthias has an idea?

**Comment by borisdiakur** [comment] 2016-12-08 08:24
Maybe this will help:

- https://confluence.atlassian.com/doc/configuring-character-encoding-174010.html
- https://confluence.atlassian.com/doc/troubleshooting-character-encodings-167194.html

**Comment by borisdiakur** [comment] 2016-12-12 11:40
@Timtam & @grimurd: Could you resolve the issue with the information linked above? If so, I would add the information to the README.md and then close the issue. If not, please tell me.

**Comment by grimurd** [comment] 2016-12-12 14:04
@borisdiakur Everything seems to be set up correctly. I ran the encoding test from the link and it passed with no problems. Everything looked just like it should.

I also checked the server, confluence and database encodings and they are all UTF-8.

**Comment by borisdiakur** [comment] 2016-12-13 09:03
Ok, I need help in reproducing the issue. Here is how you can help me:

1. Clone the repo.
2. Install the Atlassian Plugin SDK (see [documentation](https://developer.atlassian.com/docs/getting-started/set-up-the-atlassian-plugin-sdk-and-build-a-project/)).
3. Run Confluence with `atlas-run`.
4. See if you can reproduce the issue; if not, tweak the whole setup so that you can reproduce it.
5. Describe your setup in detail and optionally send me a PR; or if you could not reproduce the issue, tell me that, so I can close this issue.

**Comment by borisdiakur** [comment] 2017-04-05 21:36
In marked version 1.1.2 I have replaced the pegdown parser, which marked was perviously using under the hood, with the [flexmark-java](https://github.com/vsch/flexmark-java) parser. Please check, if it resolves this issue for you.

**Comment by grimurd** [comment] 2017-04-07 22:42
The 1.1.2 update didn't solve it for me. 

But I decided to spend my Friday night setting up a new VM with the same OS, same version of confluence and same database in order to attempt to replicate. And marked worked just fine on that install.

Gonna have to try to restore the production installation to the test install and try it that way, but it will have to wait until another night.

**Comment by Juiceful** [comment] 2020-09-11 00:04
I made a minimal fix attempt. Do you still have something to test it on @grimurd?

**Comment by Juiceful** [comment] 2021-02-01 12:14
@borisdiakur I am not getting any response from grimurd, can you perhaps review my PR?  It's basically just being more verbose with treating the buffers as UTF-8 content. It fixed the issue for us, and I do not think it's possible it should break any utf-8 native installations.

**Comment by grimurd** [comment] 2021-02-01 13:57
I can confirm it works for me now @Juiceful

**Comment by borisdiakur** [comment] 2021-02-01 19:43
@Juiceful PR merged. New version of marked released. Please try it out. Thanks for the support! 🤘🏻

**Closed as completed** 2021-02-01 19:43 UTC
